resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: main-env
  literals:
    - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    - POSTGRES_USER=postgres
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317


secretGenerator:
- name: main-secrets
  envs:
  - .main.secrets
