---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: docker.io/rodrigo0345/api-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: api-service-env
        - secretRef:
            name: api-service-secrets
      terminationGracePeriodSeconds: 180